package(default_visibility = ["//visibility:public"])

load("//protobuf:rules.bzl", "proto_language")

proto_language(
    name = "csharp",
    pb_file_extensions = [".cs"],
    output_file_style = "pascal",
    output_to_libdir = True,
)
