package(default_visibility = ["//visibility:public"])

load("//protobuf:rules.bzl", "proto_language")

proto_language(
    name = "objc",
    pb_file_extensions = [".pbobjc.h", ".pbobjc.m"],
    output_file_style = "capitalize",
)
