package(default_visibility = ["//visibility:public"])

#load("//bzl:python/rules.bzl", "py_proto_compile")

# py_proto_compile(
#     name = "protos",
#     protos = ["//examples/helloworld/proto:protos"],
# )
